### ISSUE TITLE
Criar o PG de qualidade

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#2]
Elaborar o Plano de Gerência de Qualidade

**Comment by Franciscobraz** [comment]
Link Drive Todos os Documentos :
https://drive.google.com/drive/folders/0B33uQzMtd-jSZVQxSlpnVkRvVFE?usp=sharing
Link Direto PG de Qualidade: https://docs.google.com/document/d/1nQzRZ3AvR_f8WN69rfVBwEvgWc8lTVq6F2jLiqg2W3Y/edit?usp=sharing

**Comment by zevatron** [comment]
### Identificar os padrões de qualidade relevantes para o projeto  determinação de como os satisfazer.

* Descrição dos processos de produção
* Requisitos de qualidade para aceitar entregas do projeto
* Requisitos de qualidade para aceitar entregas do produto

#### Planejamento da garantia de qualidade

- Planejar auditorias de produto, processo e de release.
- Definir métricas 
- Definir prioridades

##### Pesquisar

- Normas
	- Ex: ISO 9000/2000
- Modelos de Processo de Software
	- CMMI
	- MPS.BR
- Padrões Internacionais de Processo de Software
	- ISO 12207
- Padrões Internacionais de Qualidade de Software
	- ISO 9126
	- ISO 15504
	- ISO/IEC 25010 (SQuaRe)
