### ISSUE TITLE
Criar o PG de Escopo

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#3]
GanttStart: 2017-06-22
GanttDue: 2017-06-27

Elaborar o Plano de Gerência de Escopo

**Comment by zevatron** [comment]
Esse documento tem como base o Canvas #1 onde já estão descritos os alguns requisitos, o objetivo e o Grupo de entregas/Linha de tempo (EAP).

**Comment by zevatron** [comment]
## Requisitos
* CRUD
  * Discentes
  * Docentes 
  * Propostas de TCC / TCC
  * Agenda dos Docentes
* Níveis de permissão
* Discente após cadastrar proposta pode enviar convite para oritentador(Docente)
* Docente poderá agendar a apresentação da proposta de TCC
   * Docente deve visualizar outros professores disponíveis para formar a banca da apresentação
* Docentes da banca cadastram suas notas e comentários
* Após a proposta ser validada e aceita, segue-se o tramite para defesa do TCC
   * A proposta terá um histórico com as atividades executadas e a serem executadas
* Docente pode realizar o reagendamento caso necessário

**Comment by zevatron** [comment]
## EAP
![EAP](https://www.lucidchart.com/publicSegments/view/3734cc4a-a1c7-4099-806e-435aec3e976d/image.png)

**Comment by Franciscobraz** [comment]
Link Drive Todos os Documentos :
https://drive.google.com/drive/folders/0B33uQzMtd-jSZVQxSlpnVkRvVFE?usp=sharing
Link Direto PG de Escopo: https://docs.google.com/document/d/1lv7EeccDIp8LzKIPJR2ld1fTYjDfcGhppcWaB7rWC9o/edit?usp=sharing

**Comment by AndradeWI** [comment]
A descrição do link diz PG de Qualidade, tentei mudar mais não achei onde

**Comment by Franciscobraz** [comment]
@AndradeWI  aqui e o de escopo. , mas no link acima tem todos , e em cada issue tem o link direto pra o documento referente a issue.

**Comment by AndradeWI** [comment]
Quando acesso a link, fica uma mensagem informando que o documento está na lixeira

**Comment by AndradeWI** [comment]
Ah blz @Franciscobraz

**Comment by Franciscobraz** [comment]
Alguém deve ter colocado na lixeira sem querer, mas e só retirar, esses documentos não podem ser apagados , por favor vamos ter cuidado porque todos tem acesso máximo a tudo aqui.
