### ISSUE TITLE
Mockups/Wireframes das telas

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#33]
GanttStart: 2017-06-29
GanttDue: 2017-07-06

Utilizar alguma ferramenta de diagramação para criar algumas das principais telas...
Como sugestão podemos utilizar a ferramenta on-line https://www.draw.io/ para gerar wireframes, entre outros.

**Comment by zevatron** [comment]
@Uelo Gostaria que já fosse bolando algumas idéias para as telas do nosso sistema. Você pode ter algumas idéias do que deve ter nas telas lendo o Canvas #1  e o PG de Escopo #3. Esses dois documentos descrevem o que o sistema deverá ter.

**Comment by Uelo** [comment]
Mockup das telas de cadastro para docentes e discentes criadas. Procurei deixar o mais simples e enxuto possível. Possiveis adições/mudanças serão discutidas futuramente.

![cadastro](https://user-images.githubusercontent.com/26587268/27885045-f173ad82-61ac-11e7-8732-d933cfe99892.png)
![cadastro2](https://user-images.githubusercontent.com/26587268/27885044-f172c67e-61ac-11e7-96d3-e685cd27a4a1.png)

**Comment by Uelo** [comment]
![criacao_de_banca](https://user-images.githubusercontent.com/26587268/27890273-f97979a6-61c7-11e7-85d4-f492cda44b62.png)

**Comment by Uelo** [comment]
Idéia da tela para envio de TCC

![envio_tcc](https://user-images.githubusercontent.com/26587268/27893119-03a73c9e-61da-11e7-83e6-8e2dbcff43a0.png)

**Comment by Uelo** [comment]
Idéia para a página principal. O objetivo é deixar a interface o mais intuitiva e agradável aos olhos quanto possível, com cores mais leves e ícones grandes nos botões. Lembrando que serão adicionados mais elementos com o passar do tempo, isso é apenas um protótipo e pode ser totalmente reestruturado.

![pagina_principal](https://user-images.githubusercontent.com/26587268/27894026-1bbb8a46-61e0-11e7-9a00-1b9b8f4e2377.png)
