### ISSUE TITLE
Criar o PG de RH

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#38]
GanttStart: 2017-07-13
GanttDue: 2017-07-18

**Comment by zevatron** [comment]
Essa atividade era para ter sido entregue hoje. Quanto antes o documento for concluído melhores a chances de  aumentar a nota. 
A apresentação ficou para terça (18/07)

**Comment by zevatron** [comment]
### Plano de Gerenciamento de Recursos Humanos

###### Identificar as habilidades necessárias e as pessoas mais apropriadas.
###### Identificar as funções e responsabilidades que cada integrante da equipe irá desempenhar. E s relacionamentos hierárquicos.
######  A quantidade de pessoas pode ser definida previamente ou posteriormente após ser feita uma estimativa do tamanho do software.

- Descrição do gerenciamento de RH
- Organograma
- Dados da equipe
- Matriz de responsabilidades
-  (Opcional) Políticas:
    - Alocação/seleção de pessoal
    - Liberação
    - Capacitação
    - Avaliação

Ver Exemplo Projeto Novas Fronteira e templates

**Comment by AndradeWI** [comment]
Olhem e me digam se precisa alterar alguma coisa por favor. 
Falta os endereços de e-mail e telefone de cada um
https://github.com/IFPB-2017-1/gps/wiki/PG-de-RH
