### ISSUE TITLE
Criar o PG de Tempo

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#4]
GanttStart: 2017-06-27
GanttDue: 2017-06-29

Elaborar o Plano de Gerência de Tempo

**Comment by thomas2392** [comment]
## Processo de Gerenciamento de Tempo

* O gerenciamento de tempo será realizado usando como base o *Scrum Poker*, onde a equipe irá se reunir para definir o nível de dificuldade de cada tarefa. Cada membro irá afirmar sua estimativa usando um valor da **Sequência de Fibonacci** que irá representar uma determinada quantidade de horas, após uma discussão a equipe chegará à um concensso e o gerente irá apontar as horas na tarefa.

**Comment by Franciscobraz** [comment]
Link Drive Todos os Documentos : 
https://drive.google.com/drive/folders/0B33uQzMtd-jSZVQxSlpnVkRvVFE?usp=sharing
Link Direto PG de Tempo: https://docs.google.com/document/d/1HPA6tsskx6gqyZytaaV9MqUkQLpcoWubZcIfaiV--Ns/edit?usp=sharing

**Comment by netxande** [comment]
Modelo do PG de Tempo: 
https://drive.google.com/open?id=102wBFdavlFHA_5Dsdj4YOMJUZNfAfR6IWUF20SCbXhA

**Comment by zevatron** [comment]
Link para acesso ao gráfico de Gantt. Para acesso ao site é necessário gerar um token da sua conta no GitHub.
https://live.ganttlab.org/?l=project&p=IFPB-2017-1/gps

**Comment by zevatron** [comment]
@thomas2392 estou cadastrando as datas de início e fim de cada atividade.

**Comment by zevatron** [comment]
PG de Tempo adicionado ao Wiki.
https://github.com/IFPB-2017-1/gps/wiki
