### ISSUE TITLE
Criar o PG de Comunicação

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#45]
GanttStart: 2017-07-20
GanttDue: 2017-08-01

**Comment by zevatron** [comment]
###### Identificar as partes interessadas (INICIAÇÃO)
######  Planejar as comunicações (PLANEJAMENTO)
- Determinar as necessidades de informações e comunicações das partes
  - Ex: Determinar as atividades aos envolvidos
- Métodos de comunicação
  - INTERATIVA: reuniões, telefonemas, videoconferências
  - ATIVA(push): cartas, memos,relatórios, e-mails,...
  - PASSIVA(pull): intranet, e-learning, ...
- Identificação das necessidades de informação e comunicação dos envolvidos
  - Ex: Quem precisa da informação?
###### Distribuir as informações (EXECUÇÃO)
###### Gerenciar as expectativas das partes (EXECUÇÃO)
###### Reportar o desempenho (MONITORAMENTO)

**Comment by AndradeWI** [comment]
Conclui olhem e vejam o que precisa ser alterado ou inserir

- [Plano de Gerência da Comunicação](https://github.com/IFPB-2017-1/gps/wiki/PG-de-Comunicacao)

**Comment by zevatron** [comment]
Correção do link quebrado... https://github.com/IFPB-2017-1/gps/wiki/PG-de-Comunicacao
