### ISSUE TITLE
Criar o PG de Aquisição

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#46]
GanttStart: 2017-08-01
GanttDue: 2017-08-08

**Comment by AndradeWI** [comment]
Pensamos em colocar consultoria de jsf, caso ache outra coisa importante pode ficar a vontade para incluir
 https://drive.google.com/open?id=0B2o0kggBtCaZVm5SRF9xOE94eFU

**Comment by AndradeWI** [comment]
Esse link é um exemplo de como elaborar um PG de Aquisição.
Qualquer dúvida estou a disposição

**Comment by Uelo** [comment]
PG de Aquisição feito e postado na wiki. Desculpem pela demora.
