### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#5]
GanttStart: 2017-06-20
GanttDue: 2017-07-08

Através desse documento será possível iniciar o desenvolvimento do sistema, pois nele ficarão definidas as principais classes e seus relacionamentos.

**Comment by Franciscobraz** [comment]
Onde está o diagrama de classes ?

**Comment by zevatron** [comment]
?

**Comment by rusemberg** [comment]
Como eu coloco uma imagem aqui no comentário?

**Comment by rusemberg** [comment]
![diagramaclassesprojetogps](https://user-images.githubusercontent.com/28631278/27866996-c2bf47f0-616e-11e7-8262-62575350e8d7.png)
