### ISSUE TITLE
Gerar Projeto Maven

### ISSUE THREAD

**Issue by zevatron** [IFPB-2017-1/gps#7]
GanttStart: 2017-07-01
GanttDue: 2017-07-08

Cadastrar as dependências do projeto e subir o projeto no GitHub

**Comment by thomas2392** [comment]
Criei o projeto maven, quem for baixar so atualizar o pom.xml para pegar as bibliotecas.

**Comment by thomas2392** [comment]
Como é apenas o projeto vazio, commitei na branch master mesmo.

**Comment by zevatron** [comment]
Estou tentando usar o projeto mas na minha maquina apresentou alguns erros. Tentei corrigir mas não deu certo. Noquei também que não havia a pasta webapp. Vou criar um novo para comparar.

**Comment by zevatron** [comment]
fiz umas mudanças no repositório master. Para postar diretamente nele é preciso passar por uma revisão. O fluxo será o seguinte: -> fazer um pull do origim/master (que é o remoto) para atualizar o master local `git pull origin master.` Com o master local atualizado uma idéia é criar uma branch com seu próprio nome `git branch seunome`, entre na branch `git checkout seunome`, desenvolva nessa branch e assim essa será a branch que deverá ser enviada ao repositório `git push origin seunome`. Lá no repositório ela ira aparecer com o nome origin/"seunome" e através dessa branch deve-se abrir uma solicitação de pull request para alguém revisar e jogar no origin/master
